In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

/var/folders/r0/3ty1gxbn02q24zg2crgysbm40000gn/T/ipykernel_6326/1913378692.py:14: DeprecationWarning: version is deprecated and will be removed in Python 3.14
  print(sqlite3.version)

/* Q10: Produce a list of facilities with a total revenue less than 1000.
The output of facility name and total revenue, sorted by revenue. Remember
that there's a different cost for guests and members! */

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
            CASE WHEN b.memid = 0 THEN  SUM(b.memid * f.guestcost)
            ELSE SUM(b.memid * f.membercost) END AS total_revenue
        FROM Bookings as b
        INNER JOIN Facilities AS f
        USING(facid)
		GROUP BY name
        ORDER BY total_revenue;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 0)
('Pool Table', 0)
('Snooker Table', 0)
('Table Tennis', 0)
('Tennis Court 1', 15310)
('Massage Room 2', 25760)
('Squash Court', 33355.0)
('Massage Room 1', 37471.5)
('Tennis Court 2', 69650)

/var/folders/r0/3ty1gxbn02q24zg2crgysbm40000gn/T/ipykernel_6326/3932219822.py:14: DeprecationWarning: version is deprecated and will be removed in Python 3.14
  print(sqlite3.version)

/* Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order */

In [7]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT recommendedby, surname, firstname
        FROM Members
        ORDER BY surname, firstname;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('9', 'Bader', 'Florence')
('9', 'Baker', 'Anne')
('13', 'Baker', 'Timothy')
('3', 'Boothe', 'Tim')
('1', 'Butters', 'Gerald')
('16', 'Coplin', 'Joan')
('2', 'Crumpet', 'Erica')
('4', 'Dare', 'Nancy')
('', 'Farrell', 'David')
('', 'Farrell', 'Jemima')
('', 'GUEST', 'GUEST')
('5', 'Genting', 'Matthew')
('30', 'Hunt', 'John')
('4', 'Jones', 'David')
('11', 'Jones', 'Douglas')
('1', 'Joplette', 'Janice')
('1', 'Mackenzie', 'Anna')
('1', 'Owen', 'Charles')
('13', 'Pinker', 'David')
('2', 'Purview', 'Millicent')
('', 'Rownam', 'Tim')
('20', 'Rumney', 'Henrietta')
('15', 'Sarwin', 'Ramnaresh')
('', 'Smith', 'Darren')
('', 'Smith', 'Darren')
('1', 'Smith', 'Jack')
('', 'Smith', 'Tracy')
('6', 'Stibbons', 'Ponder')
('', 'Tracy', 'Burton')
('', 'Tupperware', 'Hyacinth')
('2', 'Worthington-Smyth', 'Henry')

/var/folders/r0/3ty1gxbn02q24zg2crgysbm40000gn/T/ipykernel_6326/1835415128.py:14: DeprecationWarning: version is deprecated and will be removed in Python 3.14
  print(sqlite3.version)

/* Q12: Find the facilities with their usage by member, but not guests */

In [10]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
        	CASE WHEN b.memid != 0 THEN COUNT(b.facid)
        	END AS member_booking_count
        FROM Bookings AS b
        INNER JOIN Facilities as f
        USING(facid)
        GROUP BY name;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 383)
('Massage Room 1', 629)
('Massage Room 2', None)
('Pool Table', 836)
('Snooker Table', 444)
('Squash Court', None)
('Table Tennis', 403)
('Tennis Court 1', 408)
('Tennis Court 2', None)

/var/folders/r0/3ty1gxbn02q24zg2crgysbm40000gn/T/ipykernel_6326/3071440531.py:14: DeprecationWarning: version is deprecated and will be removed in Python 3.14
  print(sqlite3.version)

/* Q13: Find the facilities usage by month, but not guests */

In [13]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
				strftime('%m', starttime) AS month,
	CASE WHEN b.memid != 0 THEN COUNT(b.facid)
	END AS member_booking_count
FROM Bookings AS b
INNER JOIN Facilities as f
USING(facid)
GROUP BY  month, name
ORDER BY member_booking_count DESC;
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', '09', 435)
('Pool Table', '08', 291)
('Massage Room 1', '09', 282)
('Massage Room 1', '08', 224)
('Snooker Table', '09', 210)
('Table Tennis', '09', 205)
('Badminton Court', '09', 181)
('Snooker Table', '08', 159)
('Tennis Court 2', '08', 149)
('Table Tennis', '08', 147)
('Badminton Court', '08', 146)
('Tennis Court 1', '08', 146)
('Massage Room 1', '07', 123)
('Pool Table', '07', 110)
('Tennis Court 1', '07', 88)
('Snooker Table', '07', 75)
('Badminton Court', '07', 56)
('Table Tennis', '07', 51)
('Massage Room 2', '08', 40)
('Massage Room 2', '07', None)
('Squash Court', '07', None)
('Tennis Court 2', '07', None)
('Squash Court', '08', None)
('Massage Room 2', '09', None)
('Squash Court', '09', None)
('Tennis Court 1', '09', None)
('Tennis Court 2', '09', None)

/var/folders/r0/3ty1gxbn02q24zg2crgysbm40000gn/T/ipykernel_6326/3344157347.py:14: DeprecationWarning: version is deprecated and will be removed in Python 3.14
  print(sqlite3.version)